### ISSUE TITLE
Wont parse big xml files.

### ISSUE THREAD

**Issue by instalab** [NaturalIntelligence/fast-xml-parser#126]
### Checklist

* [X] Are you running the latest version? (3.12.5)
* [X] Have you checked if you are using correct configuration? (Different configurations, including the default one wont work)
* [X] Did you try online [tool](https://naturalintelligence.github.io/fast-xml-parser/)? (Not working either)

 
### Input
This file: https://raw.githubusercontent.com/gtk-rs/gir-files/master/GLib-2.0.gir

### Code
```js
const fs = require('fs')
const xmlData = fs.readFileSync('GLib-2.0.gir').toString()
const tObj = fastXmlParser.getTraversalObj(xmlData)
```

### Output
Browser:
```
xmlNode.js:11 Uncaught TypeError: this.child[t.tagname].push is not a function
    at t.exports.addChild (xmlNode.js:11)
    at Object.e.getTraversalObj (xmlstr2xmlnode.js:90)
    at Object.e.parse (parser.js:10)
    at HTMLButtonElement.<anonymous> ((index):74)
    at HTMLButtonElement.dispatch (jquery-3.2.1.min.js:3)
    at HTMLButtonElement.q.handle (jquery-3.2.1.min.js:3)
```
Node.js
```
/home/user/github/GirExtractor/node_modules/fast-xml-parser/src/xmlNode.js:11
            this.child[child.tagname].push(child);
                                      ^

TypeError: this.child[child.tagname].push is not a function
    at module.exports.addChild (/home/user/github/GirExtractor/node_modules/fast-xml-parser/src/xmlNode.js:11:39)
    at Object.getTraversalObj (/home/user/github/GirExtractor/node_modules/fast-xml-parser/src/xmlstr2xmlnode.js:90:25)
    at Object.<anonymous> (/home/user/github/GirExtractor/gir/read.js:37:28)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:760:12)
    at startup (internal/bootstrap/node.js:308:19)
```

### expected data
Something that's not an error.

**Would you like to work on this issue?**

- [ ] Yes
- [X] No (Sorry, lacking time)

[Bookmark](https://github.com/NaturalIntelligence/fast-xml-parser/stargazers) this repository for further updates.

**Comment by amitguptagwl** [comment]
This utility has been tested up to 98 mb file. Can you please tell us the file size you tested with? And how to open/convert the linked file?

**Comment by instalab** [comment]
The file is roughly 2 Megabytes in size.
The linked file is just an XML, it simply has a different extension (.gir), you can open it and you'll see XML data in it, not need to convert anything. I tried opening it in PHP using simplexml_load_string() function and it worked flawlessly. I just need to do the same in JS now.

**Comment by amitguptagwl** [comment]
ok let me try that. thanks

**Comment by amitguptagwl** [comment]
I've found that the issue occurs while parsing a doc tag at line 4372 in your file. Let me see how it can be fixed.

**Comment by amitguptagwl** [comment]
Done. Please use 3.12.7
