### ISSUE TITLE
getting confusing error "isAttribute is not defined" when trying to convert JSON to XML.

### ISSUE THREAD

**Issue by jinq102030** [NaturalIntelligence/fast-xml-parser#140]
I need to use this module for a project to do some processing on XML --> JSON --> XML. Would really appreciate if there is an existing example for this.

Created a simple code snippet based on the two examples (xml --> json,  json --> xml),   however I got error on the following xml https://raw.githubusercontent.com/GovReady/govready/master/prototypes/ssg-rhel6-oval.xml

I guess something is wrong with xmlOptions, but I am not sure what.  
```
$ node delme.js ssg-rhel6-oval.xml | more
/Users/jdole/learn/node/delme.js:40
    attrValueProcessor: a=> he.encode(a, {isAttributeValue: isAttribute, useNamedReferences: true})// default is a=>a
                                                            ^

ReferenceError: isAttribute is not defined
    at Object.attrValueProcessor (/Users/jdole/learn/node/delme.js:40:61)
    at Parser.j2x (/Users/jdole/learn/node/node_modules/fast-xml-parser/src/json2xml.js:137:67)
    at Parser.j2x (/Users/jdole/learn/node/node_modules/fast-xml-parser/src/json2xml.js:140:37)
    at Parser.parse (/Users/jdole/learn/node/node_modules/fast-xml-parser/src/json2xml.js:73:17)
    at Object.<anonymous> (/Users/jdole/learn/node/delme.js:43:15)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

Here is the code snippet
```
var x2jparser = require('fast-xml-parser');
var j2xParser = require("fast-xml-parser").j2xParser;
var he = require('he');
var fs=require("fs");

var jsonOptions = {
    attributeNamePrefix : "@_",
    attrNodeName: "attr", //default is 'false'
    textNodeName : "#text",
    ignoreAttributes : false,
    ignoreNameSpace : false,
    allowBooleanAttributes : false,
    parseNodeValue : true,
    parseAttributeValue : false,
    trimValues: true,
    cdataTagName: "__cdata", //default is 'false'
    cdataPositionChar: "\\c",
    localeRange: "", //To support non english character in tag/attribute values.
    parseTrueNumberOnly: false,
    attrValueProcessor: a => he.decode(a, {isAttributeValue: true}),//default is a=>a
    tagValueProcessor : a => he.decode(a) //default is a=>a
};
xml=fs.readFileSync(process.argv[2], "utf8");

var jsonObj = x2jparser.parse(xml,jsonOptions);
//console.log(JSON.stringify(jsonObj))
//process.exit();

var xmlOptions = {
    attributeNamePrefix : "@_",
    attrNodeName: "attr", //default is false
    textNodeName : "#text",
    //ignoreAttributes : true,
    cdataTagName: "__cdata", //default is false
    cdataPositionChar: "\\c",
    format: false,
    indentBy: "  ",
    supressEmptyNode: false,
    tagValueProcessor: a=> he.encode(a, { useNamedReferences: true}),// default is a=>a
    attrValueProcessor: a=> he.encode(a, {isAttributeValue: isAttribute, useNamedReferences: true})// default is a=>a
};
var parser = new j2xParser(xmlOptions);
rxml = parser.parse(jsonObj);
console.log(rxml)
```

**Comment by amitguptagwl** [comment]
Sorry to be harsh but with the experience of last 2 issues you raised, we're available to complete your homework. You can raise an issue on stackoverflow.
